In [1]:
import numpy as np

a=np.random.randn(5)

In [2]:
print(a)

[-3.04883249 -0.24572299  1.8577848   0.46754782 -0.01908561]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-3.04883249 -0.24572299  1.8577848   0.46754782 -0.01908561]


In [6]:
print(np.dot(a,a.T))

13.02608896964804


In [8]:
a=np.random.randn(5,1)
print(a)

[[-0.66402792]
 [-1.0285914 ]
 [-0.65926811]
 [ 0.62077912]
 [-0.29609584]]


In [9]:
print(a.T)

[[-0.66402792 -1.0285914  -0.65926811  0.62077912 -0.29609584]]


In [10]:
print(np.dot(a,a.T))

[[ 0.44093308  0.68301341  0.43777244 -0.41221467  0.19661591]
 [ 0.68301341  1.05800027  0.67811751 -0.63852806  0.30456164]
 [ 0.43777244  0.67811751  0.43463445 -0.40925988  0.19520655]
 [-0.41221467 -0.63852806 -0.40925988  0.38536671 -0.18381012]
 [ 0.19661591  0.30456164  0.19520655 -0.18381012  0.08767275]]
